version: '3'

# $ docker-compose -f docker-compose-dev.yml build
# $ docker-compose -f docker-compose-dev.yml up -d


services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_buffers=32MB", "-c", "max_connections=10", "-c", "work_mem=2MB", "-c", "maintenance_work_mem=16MB", "-c", "huge_pages=off"]
     # メモリ設定の追加
     # lightsailのメモリ設定は1GBのため、メモリ使用量を軽減する

  gunicorn:
    build: .
    image: gunicorn:20.1.0
    container_name: gunicorn
    volumes:
      - .:/code/
      - gunicorn:/var/run/gunicorn
    env_file: secret.env
    stdin_open: true
    tty: true
    depends_on:
      - db

  nginx:
    image: nginx:1.17.7
    container_name: nginx
    depends_on:
      - gunicorn
    ports:
      - "8000:8000"
    volumes:
      - ./gunicorn.conf:/etc/nginx/conf.d/default.conf
      - ./static_root:/var/www/static
      - gunicorn:/var/run/gunicorn

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    container_name: cron
    volumes:
      - .:/code/
    env_file: secret.env
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_data:
  gunicorn:
    driver: local